name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  release_please:
    name: Release Please
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.repository == 'devtomio/thread-amount'

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: google-github-actions/release-please-action@141edfb4d3a003bc1723056c9ab59ba000ec22c8 # tag=v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust

  cargo_publish:
    name: Publish Cargo Package
    runs-on: ubuntu-latest
    needs: release_please
    if: ${{ needs.release_please.outputs.release_created == 'true' }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1.0.7
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
