name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        name:
          - Stable
          - Beta
          - Nightly
          - MacOS
          - Windows
        
        include:
          - name: Stable
            toolchain: stable
            os: ubuntu-latest

          - name: Beta
            toolchain: beta
            os: ubuntu-latest

          - name: Nightly
            toolchain: nightly
            os: ubuntu-latest

          - name: MacOS
            toolchain: stable
            os: macOS-latest

          - name: Windows
            toolchain: stable
            os: windows-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install Nextest
        uses: taiki-e/install-action@740a936627d24a66436d6a4fc358cb5b3d4b79c5 # nextest

      - name: Run Tests
        run: cargo nextest run

  freebsd-test:
    name: Unit Tests (FreeBSD)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run Tests
        uses: vmactions/freebsd-vm@5a72679103d223925653750faa878a143340fbd0 # v1
        env:
          RUSTUP_HOME: /usr/local/rustup
          CARGO_HOME: /usr/local/cargo
          RUSTUP_IO_THREADS: 1
        with:
          envs: 'RUSTUP_HOME CARGO_HOME RUSTUP_IO_THREADS'
          usesh: true
          mem: 3000
          prepare: |
            pkg install -y curl python2
            curl https://sh.rustup.rs -sSf --output rustup.sh
            sh rustup.sh -y --profile minimal --default-toolchain stable
            export PATH="/usr/local/cargo/bin:$PATH"
            rustc --version
          run: |
            export PATH="/usr/local/cargo/bin:$PATH"
            cargo test -- --test-threads=1

  openbsd-test:
    name: Unit Tests (OpenBSD)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
  
      - name: Run Tests
        uses: vmactions/openbsd-vm@c941015845c0f0c429676840963dc63b226d4f69 # v1
        with:
          usesh: true
          mem: 3000
          prepare: |
            pkg_add rust
            rustc --version
            cargo --version
          run: |
            cargo test -- --test-threads=1

  netbsd-test:
    name: Unit Tests (NetBSD)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
  
      - name: Run Tests
        uses: vmactions/netbsd-vm@1d9767765fd3f986e6de3aff4b1148f0c3a45f01 # v1
        with:
          usesh: true
          mem: 3000
          prepare: |
            export PATH="/usr/pkg/sbin:/usr/pkg/bin:$PATH"
            pkg_add curl
            curl https://sh.rustup.rs -sSf --output rustup.sh
            ftp -o rustup.sh https://sh.rustup.rs
            sh rustup.sh -y --profile minimal --default-toolchain stable
            export PATH="$HOME/.cargo/bin:$PATH"
            rustc --version
            cargo --version
          run: |
            export PATH="$HOME/.cargo/bin:$PATH"
            cargo test -- --test-threads=1

  wasm-check:
    name: Build (Wasm)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
  
      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
  
      - name: Cache dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
  
      - name: Check Wasm compatibility
        run: cargo check --target wasm32-unknown-unknown

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run rustfmt
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # tag=v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings
